#!/bin/bash
#PBS -N vol_test
#PBS -l select=1:ncpus=1:mpiprocs=1
#PBS -l walltime=00:01:00
#PBS -j oe
#PBS -A ECP-EZ

cd $PBS_O_WORKDIR

echo "Job started on $(date)"
echo "Running on: $(hostname)"

echo "Loading modules"
module load gcc/8.5.0-ede2bck
module load openmpi/4.1.1-by6rv67
module load hdf5/1.10.7-zjwj3y2

echo "Building"
rm -rf build

env LD_LIBRARY_PATH="" /usr/bin/cmake -S . -B build -DCMAKE_C_COMPILER=mpicc
env LD_LIBRARY_PATH="" /usr/bin/cmake --build build -j8

echo "Running small test..."
./build/test_write

echo "Job finished on $(date)"