#!/bin/bash
#PBS -N vol_test
#PBS -l select=1:ncpus=8:mpiprocs=1
#PBS -l walltime=00:05:00
#PBS -j oe
#PBS -A ECP-EZ
#PBS -q bdwall

cd $PBS_O_WORKDIR/..

source /lcrc/project/ECP-EZ/public/compression/libpressio/use_spack.sh

LP_VIEW=/lcrc/project/ECP-EZ/public/compression/libpressio/libpressio_env/.spack-env/view

echo "Building"
rm -rf build
cmake -S . -B build \
    -DCMAKE_C_COMPILER=mpicc \
    -DUSE_CUDA=OFF \
    -DCMAKE_PREFIX_PATH="$LP_VIEW"
cmake --build build -j8

export HDF5_VOL_CONNECTOR="pass_through_ext under_vol=0;under_info={}"
export HDF5_PLUGIN_PATH=$(pwd)/build

echo "=== Small write test ==="
./build/tests/test_cpu_write

echo "=== Hurricane test ==="
./build/tests/test_cpu_hurricane