#!/bin/bash
#PBS -N vol_test
#PBS -l select=1:ncpus=1:mpiprocs=1
#PBS -l walltime=00:02:00
#PBS -j oe
#PBS -A ECP-EZ

cd $PBS_O_WORKDIR

echo "Job started on $(date)"
echo "Running on: $(hostname)"

source /lcrc/project/ECP-EZ/public/compression/libpressio/use_spack.sh

LP_VIEW=/lcrc/project/ECP-EZ/public/compression/libpressio/libpressio_env/.spack-env/view

echo "Building"
rm -rf build
cmake -S . -B build \
    -DCMAKE_C_COMPILER=mpicc \
    -DCMAKE_PREFIX_PATH="$LP_VIEW"
cmake --build build -j8

echo "Running small test..."
export HDF5_VOL_CONNECTOR="pass_through_ext under_vol=0;under_info={}"
export HDF5_PLUGIN_PATH=$(pwd)/build
./build/test_hurricane

echo "Job finished on $(date)"